check for holiday file

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -17,14 +17,18 @@ jobs:
 
   check-files:
     runs-on: ubuntu-latest
-    needs: 
-      - random-exit
     
     steps:
       - name: Make sure change is on holiday files only
         run: | 
           updated_files=$(gh pr view "$PR_URL" --json files --jq '.files.[].path')
-          echo $updated_files
+          for f in $updated_files; do
+            echo $f
+            if [[ ! $f =~ ^holiday/[a-zA-Z0-9_]+.dat$ ]]; then
+              echo "${f} is not a holiday file. Failing test..."
+              exit 1
+            fi
+          done
 
         env:
           PR_URL: ${{github.event.pull_request.html_url}}
@@ -33,6 +37,7 @@ jobs:
   automerge:
     runs-on: ubuntu-latest
     needs:
+      - random-exit
       - check-files
 
     steps:
